---
- hosts: ibm
  gather_facts: False
  become: True
  become_user: root
  vars:
    password: $6$q.Iq9IwnwF66hTXu$VG.ajC8uIKaPlKwqnJ6sK7UiI9Uv4C7dI60X32uEKdZVkJFz9mkfGEKd3nqSBkWJmAjMSKF/PbTPGqvEi7eVB/
  tasks:
  - name: del user "oracle"
    user: name=oracle state=absent remove=yes

  - name: del user "grid"
    user: name=grid state=absent remove=yes

  - name: del group "oinstall"
    group: name=oinstall state=absent

  - name: del group "asmadmin"
    group: name=asmadmin state=absent

  - name: del group "asmdba"
    group: name=asmdba state=absent

  - name: del group "asmoper"
    group: name=asmoper state=absent

  - name: del group "dba"
    group: name=dba state=absent

  - name: del group "oper"
    group: name=oper state=absent

  - name: del group "oracle"
    group: name=oracle state=absent

  - name: add group "oinstall" gid=54321
    group: gid=54321 name=oinstall

  - name: Creating the OSDBA Group for Database Installations - add group "dba" gid=54322
    group: gid=54322 name=dba

  - name: Creating an OSOPER Group for Database Installations - add group "oper" gid=54323
    group: gid=54323 name=oper

  - name: Creating the OSBACKUPDBA Group for Database Installations - add group "backupdba" gid=54324
    group: gid=54324 name=backupdba

  - name: Creating the OSDGDBA Group for Database Installations - add group "dgdba" gid=54325
    group: gid=54325 name=dgdba

  - name: Creating the OSKMDBA Group for Database Installations - add group "kmdba" gid=54326
    group: gid=54326 name=kmdba

  - name: add group "asmdba" gid=54327
    group: gid=54327 name=asmdba

  - name: Creating the OSOPER for ASM Group - add group "asmaoper" gid=54328
    group: gid=54328 name=asmoper

  - name: Creating the OSASM Group - add group "asmadmin" gid=54329
    group: gid=54329 name=asmadmin

  - name: Creating the OSRACDBA Group for Database Installations - add group "racdba" gid=54330
    group: gid=54330 name=racdba

  - name: add user "oracle" uid=54321
    user: uid=54321 name=oracle group=oinstall home=/home/oracle groups=dba,oper,asmdba,asmadmin,asmoper password=item.password

  - name: add user "grid" uid=54322
    user: uid=54322 name=grid group=oinstall home=/home/grid groups=asmadmin,asmdba,asmoper,dba password=item.password