---
- hosts: ibm
  gather_facts: False
  become: True
  become_user: root
  vars:
    users:
    - password: "$6$z8n25vFScBvRyn31$HZY/05kVPyjnFGWfC8BM0MBVP39VHjalSgpzvsfGvwVOJUn.1QlEZ0UDC88YHtXVVggD/6NfubAxpoCAJgWto1"
  
  tasks:
  - name: Create demo user
    user: 
        name: demo
        shell: /bin/bash
        createhome: yes
        password: " item.password "
    with_items: " users "